Spec updates to accommodate arbitrary resources
ngageoint/seed pull request #40
Opened 2017-07-25 20:49 UTC by gisjedi

2017-07-25 21:06 UTC, dfaller requested changes

2017-07-25 21:06 UTC, dfaller commented on spec/sections/standard.adoc
> +resource required by the job. When dealing with `mem` and `disk` reserved
Unfinished sentence?

2017-07-25 21:06 UTC, dfaller commented on spec/sections/standard.adoc
> +which input data size (in MiBs) is multiplied and added to the constant value for resource.
I don't think specifying MiBs is necessary (it's just input file size times multiplier).

2017-07-25 21:06 UTC, dfaller commented on spec/sections/standard.adoc
> +`disk`, the following computes the resource requirement:
I would say something like "total input file size" or explain that it is the total size of all input files instead of using the term "volume". I personally find that term more confusing.

2017-07-25 21:06 UTC, dfaller commented on spec/sections/standard.adoc
> +<1> Recommended Scalar element demonstrating single constant scalar value for specify CPU requirement of job.
specifying

2017-07-25 21:06 UTC, dfaller commented on spec/sections/usage.adoc
>  * JOB_OUTPUT_DIR: Absolute path where all output products MUST be placed by job for Seed executor capture.
I was thinking we should change this to "OUTPUT_DIR" or "SEED_OUTPUT_DIR". Thoughts?

2017-07-25 21:06 UTC, dfaller commented on spec/sections/usage.adoc
> +computed resource allocation as defined in the `scalar` element under <<resources-section,Resources object>>.
We should clarify between total allocated disk, disk allocated for input, and disk allocated for output. For example, the formula (const + mult * input size) calculates the needed disk for OUTPUT; you must still add the input size again for total disk required by the algorithm. I would think we would want the env var to reflect the total disk space (input + output) needed. We could have multiple env vars for disk too.

2017-07-25 21:43 UTC, gisjedi commented on spec/sections/usage.adoc
>  * JOB_OUTPUT_DIR: Absolute path where all output products MUST be placed by job for Seed executor capture.
Totally agree. Done.

2017-07-25 22:11 UTC, gisjedi commented on spec/sections/usage.adoc
> +computed resource allocation as defined in the `scalar` element under <<resources-section,Resources object>>.
Okay, so this be my lack of understanding of the inner workings of the system, but I'm of the opinion that input size isn't really a constraint. The job itself doesn't actually ever contain that input data within itself as we volume mount it in. That isn't to say we don't copy it somewhere that is accessible, but it isn't physically residing within the context, it's merely a reference.

That said, I do agree making the information available to the context is fine, but I think that falls more in the "nice to have" category.

2017-07-26 14:46 UTC, dfaller commented on spec/sections/usage.adoc
> +computed resource allocation as defined in the `scalar` element under <<resources-section,Resources object>>.
I'm fine with the formula and env var for disk meaning the output space needed by the algorithm, I just think we need to make that clear in the documentation. Any framework running the algorithm is going to also care about input file size needed.

2017-07-26 17:12 UTC, dfaller approved these changes
LGTM

2017-07-27 00:24 UTC, merged