Issue 6 - Modifying the settings object
ngageoint/seed pull request #7
Opened 2017-03-21 20:30 UTC by mikenholt

Jonathan - 

- Removed references to the `value` tag under the settings object as the Dockerfile shouldn't contain any actual settings values.  The name will be used to correlate to a database and replace the other instances of that same name throughout the definition.  
- Added a `secret` flag for settings to indicate if that value is in Vault. 

- Do you think we need a `required` flag for settings?  I thought we talked about this and determined that if it isn't required it won;'t be in the interface when someone defines it.  If you want that in there I can add it.

2017-03-21 21:56 UTC, gisjedi commented on sections/standard.adoc
> +  "secret": true, // <1>
Association to comment is incorrect.

2017-03-21 22:01 UTC, gisjedi commented
I'm open to the addition of a `required` flag if we can come up with a need for it. I think in general the settings should always be required, as they are currently intended for required configuration such as database connection strings, access keys / etc. There is no optional state for these as the jobs entire purpose is dependent on them being set.

2017-03-21 22:01 UTC, gisjedi requested changes
Minor comment association - otherwise LGTM.

2017-03-22 13:21 UTC, mikenholt commented
Made minor change as suggested.  

I agree, I can not think of a use case for the required tag.

2017-03-22 13:48 UTC, gisjedi approved these changes

2017-03-22 13:50 UTC, merged